plugins { id 'com.android.application' }
android {
    namespace 'io.github.mekhontsev.x11example'
    compileSdk 37
    defaultConfig {
        applicationId 'io.github.mekhontsev.x11example'
        minSdk 34
        targetSdk 36
        versionCode 1
        versionName '1.0'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
dependencies { implementation project(':embedded') }
